spring:
  application:
    name: banking
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/finMaster
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
    web: WARN
    root: INFO
    com.ust.user_service: DEBUG
  pattern: "%msg%n"

server:
  port: 8200