spring:
  application:
    name: banking
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/finMaster
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
    web: WARN
    root: INFO
    com.ust.user_service: DEBUG
  pattern: "%msg%n"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html # http://localhost:8200/swagger-ui/index.html
  use-management-port: false
  show-actuator: true


server:
  port: 8200